name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./build-scripts/setup-mac.sh
    - name: make build
      run: make build
      
  test:

    runs-on: macos-latest
    
    steps:
    - name: make build-test
      run: make check
    - name: make run-tests
      run: make run-test
