name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: configure
      run: ./build-scripts/setup-mac.sh
    - name: make build
      run: make build

  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: configure
      run: ./build-scripts/setup-mac.sh
    - name: make build-test
      run: make build-test
    - name: make run-tests
      run: make run-tests

  coverage:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: configure
      run: ./build-scripts/setup-mac.sh
    - name: build coverage
      run: make build-coverage
    - name: run coverage
      run: make run-coverage
    - name: upload report
      uses: actions/upload-artifact@v7
      with:
        name: coverage-report
        path: coverage/
        retention-days: 14
